---
- name: provision a vagrant box as a development machine.
  hosts: default
  remote_user: vagrant
  vars:
    - become_user: vagrant
    - project_base: /vagrant
    - app_root: /vagrant
    - rails_env: development
    - ruby_version: '2.4.1'
    - rails_version: '5.1.2'
    - fits_version: '1.0.5'
    - solr_version: '6.6.0'
    - fcrepo_version: '4.7.4'

  roles:
    - { role: packages }
    - { role: vagrant_setup }
    - { role: set_timezone, timezone: America/Chicago }
    - { role: ffmpeg }
    - { role: imagemagick }
#    - { role: rvm }
#    - { role: samvera-tutorials }
