---
- name: provision a vagrant box as a development machine.
  hosts: default
  remote_user: vagrant
  vars:
    - become_user: vagrant
    - project_base: /vagrant
    - app_root: /vagrant
    - rails_env: development
    - ruby_version: '2.3.4'
    - rails_version: '5.0.2'
    - fits_version: '0.10.2'
    - solr_version: '6.5.0'
    - fcrepo_version: '4.7.1'

  # The following lines guard against minimal Ubuntu distributions that don't have python installed
  gather_facts: False
  pre_tasks:
    - name: install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      become: true
    - setup: # aka gather_facts

  # Set up the Machine
  roles:
    - { role: packages }
    - { role: set_timezone }
    - { role: system_setup }
    - { role: openjdk1_8 }
    - { role: ffmpeg }
    - { role: imagemagick }
    - { role: rvm }
    - { role: hydra-tutorials }
