---
- name: provision a vagrant box as a development machine.
  hosts: default
  remote_user: vagrant
  vars:
    - become_user: vagrant
    - project_base: /vagrant
    - app_root: /vagrant
    - rails_env: development
    - ruby_version: '2.3.4'
    - rails_version: '5.0.2'
    - fits_version: '0.10.2'
    - solr_version: '6.5.0'
    - fcrepo_version: '4.7.1'

  roles:
    - { role: packages }
    - { role: set_timezone }
    - { role: system_setup }
    - { role: openjdk1_8 }
    - { role: ffmpeg }
    - { role: imagemagick }
    - { role: rvm }
    - { role: hydra-tutorials }
