---
- name: provision a vagrant box as a development machine.
  hosts: default
  remote_user: vagrant
  vars:
    - become_user: vagrant
    - project_base: /vagrant
    - app_root: /vagrant
    - rails_env: development
    - ruby_version: '2.4.2'
    - rails_version: '5.1.2'
    - fits_version: '1.0.5'
    - imagemagick_ver: '7.0.7'
    - gs_ver: '9.19'
    - openjpg_ver: '2.1.0'
    - libtiff_ver: '4.0.5'
    - libpng_ver: '1.6.28'
    - solr_version: '6.6.2'
    - fcrepo_version: '4.7.4'

  roles:
    - { role: packages }
    - { role: vagrant_setup }
    - { role: set_timezone, timezone: America/Chicago }
    - { role: ffmpeg }
    - { role: imagemagick }
    - { role: rvm_io.ruby,
        rvm1_rubies: [ 'ruby-{{ ruby_version }}' ],
        rvm1_user: vagrant                            # Need root account to access system location
      }    
#    - { role: samvera-tutorials }
