---
- name: provision a vagrant box as a development machine.
  hosts: vagrant
  remote_user: vagrant
  vars:
    - become_user: vagrant
    - project_base: /vagrant
    - app_root: /vagrant
    - rails_env: development

  roles:
    - { role: packages }
    - { role: set_timezone }
    - { role: system_setup }
    - { role: openjdk1_8 }
    - { role: ffmpeg }
    - { role: imagemagick, libpng_ver: '1.6.25' }
    - { role: sufia_dependencies/install, fits_version: '0.10.2' }
    - { role: rvm, rails_version: '5.0.0.1' }
    - { role: hydra-tutorials }
