---
- name: provision a vagrant box as a development machine.
  hosts: vagrant
  remote_user: vagrant
  vars:
    - become_user: vagrant
    - project_base: /vagrant
    - app_root: /vagrant
    - rails_env: development

  roles:
    - { role: packages }
    - { role: set_timezone }
    - { role: system_setup }
    - { role: openjdk1_8 }
    - { role: ffmpeg }
    - { role: imagemagick }
    - { role: sufia_dependencies/install, fits_version: '0.6.2' }
    - { role: rvm }
    - { role: hydra-tutorials }
    # - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True, rvm1_install_flags: '--auto-dotfiles --user-install', rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm' }
    # - { role: bundler }



