---
# ROLE: samvera-tutorials
# roles/samvera-tutorials/tasks/hyrax-setup.yml
#
# Pre-load gem dependencies required by Hyrax-based tutorials
#

- name: disable gem documentation
  lineinfile: "dest=~/.gemrc line='gem: --no-document' create=yes state=present"

- name: install rails version to use for Hydra tutorials
  command: ".rvm/bin/rvm all do gem install rails -v {{ rails_version }}"

- name: clone code for Duke2018 tutorials
  git: 
    repo: https://github.com/RepoCamp/berlin2018.git
    dest: hyrax-sample
    version: walkthrough

- name: bundle install Hyrax dependencies
  command: "~/.rvm/bin/rvm all do bundle install --gemfile ~/hyrax-sample/Gemfile" 
  
- name: pre-run the db migrations for Hyrax
  command: bash -lc "cd ~/hyrax-sample/ && rails db:migrate"   

- name: set up the default collections tuypes
  command: bash -lc "cd ~/hyrax-sample/ && rails hyrax:default_collection_types:create"   

- name: run redis
  service: name=redis-server state=started
  become: yes

- name: start the hyrax development server
  command: bash -lc "cd ~/hyrax-sample/ && rails hydra:server "
  async: 3600 
  poll: 0
  
- name: wait for development server to spin up
  wait_for:
    port: 3000
    delay: 10

- name: configure default admin set for Hyrax
  command: bash -lc "cd ~/hyrax-sample/ && rails hyrax:default_admin_set:create"

- name: configure default workflows for Hyrax
  command: bash -lc "cd ~/hyrax-sample/ && rails hyrax:workflow:load"
